// Turns the demo data in src/data into supabase/seed.sql.
// Run with:  npm run db:seed-sql
import { writeFileSync } from 'node:fs';
import { categories } from '../src/data/categories';
import { packages } from '../src/data/packages';
import { blogPosts, faqs, galleryItems, testimonials } from '../src/data/content';

const q = (v: unknown): string => {
  if (v === null || v === undefined || v === '') return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

function insert(table: string, rows: Record<string, unknown>[]) {
  if (!rows.length) return '';
  const cols = Object.keys(rows[0]);
  const values = rows.map((r) => `  (${cols.map((c) => q(r[c])).join(', ')})`).join(',\n');
  return `insert into public.${table} (${cols.join(', ')}) values\n${values};\n\n`;
}

let sql = `-- Generated by scripts/generate-seed-sql.ts from src/data — do not edit by hand.
-- Run after schema.sql in Supabase → SQL Editor.

truncate public.bookings, public.enquiries, public.package_batches, public.packages, public.categories,
  public.testimonials, public.faqs, public.gallery_items, public.blog_posts cascade;

`;

sql += insert(
  'categories',
  categories.map((c) => ({ slug: c.slug, title: c.title, display_title: c.displayTitle, description: c.description, image_url: c.image ?? null, scene: c.scene, sort_order: c.sortOrder })),
);

sql += insert(
  'packages',
  packages.map((p) => ({
    slug: p.slug,
    title: p.title,
    tagline: p.tagline ?? null,
    category_slug: p.categorySlug,
    region: p.region,
    level: p.level,
    duration_days: p.durationDays,
    duration_nights: p.durationNights,
    altitude: p.altitude ?? null,
    age_group: p.ageGroup,
    gender: p.gender,
    price: p.price,
    original_price: p.originalPrice,
    short_description: p.shortDescription,
    overview: p.overview,
    highlights: p.highlights,
    images: p.images,
    scene: p.scene,
    inclusions: p.inclusions,
    exclusions: p.exclusions,
    things_to_carry: p.thingsToCarry,
    itinerary: p.itinerary,
    pickup_points: p.pickupPoints,
    faqs: p.faqs,
    policies: p.policies,
    map_query: p.mapQuery,
    featured: p.featured,
    sort_order: p.sortOrder,
  })),
);

sql += insert(
  'package_batches',
  packages.flatMap((p) => p.batches.map((b) => ({ id: b.id, package_slug: p.slug, start_date: b.startDate, end_date: b.endDate, price: b.price, seats_total: b.seatsTotal, seats_left: b.seatsLeft }))),
);

sql += insert('testimonials', testimonials.map((t) => ({ id: t.id, name: t.name, trip: t.trip, rating: t.rating, quote: t.quote })));
sql += insert('faqs', faqs.map((f, i) => ({ id: f.id, question: f.question, answer: f.answer, category: f.category, sort_order: i })));
sql += insert('gallery_items', galleryItems.map((g, i) => ({ id: g.id, title: g.title, location: g.location, image_url: g.image ?? null, scene: g.scene, sort_order: i })));
sql += insert(
  'blog_posts',
  blogPosts.map((b) => ({ slug: b.slug, title: b.title, excerpt: b.excerpt, body: b.body, author: b.author, published_at: b.publishedAt, read_minutes: b.readMinutes, tags: b.tags, image_url: b.image ?? null, scene: b.scene })),
);

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`Wrote supabase/seed.sql (${(sql.length / 1024).toFixed(1)} KB)`);
